run:
  # timeout for analysis
  deadline: 4m
  build-tags:
    - autopilotrpc
    - chainrpc
    - invoicesrpc
    - routerrpc
    - signrpc
    - walletrpc
    - watchtowerrpc
    - wtclientrpc

linters-settings:
  govet:
    # Don't report about shadowed variables
    check-shadowing: false
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

linters:
  disable-all: true
  enable:
    - gofmt
    - golint
    - govet
    - unused
