language: go
go:
  - 1.6.3
  - 1.7
sudo: false
install:
  - go get -v github.com/roasbeef/btcd # Required for the rpc test package.
  - go get -v github.com/Masterminds/glide
  - glide install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - export GO15VENDOREXPERIMENT=1
  - go test -v $(GO15VENDOREXPERIMENT=1 go list ./... | grep -v '/vendor/')
