language: go
go:
  - 1.7.5
  - 1.8
sudo: false
install:
  - go get -v github.com/roasbeef/btcd # Required for the rpc test package.
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./gotest.sh -l -r -c
