language: go
go:
  - "1.9.4"
  - "1.10"
sudo: required
install:
  - sudo add-apt-repository -y ppa:bitcoin/bitcoin -y
  - sudo apt-get update -q
  - sudo apt-get install bitcoind -y
  - export PATH=$PATH:$PWD/linux-amd64/
env:
  matrix:
    - RACE=false
    - RACE=true
script:
  - export PATH=$PATH:$GOPATH/bin
  - make travis
after_script:
  - find *.log | xargs -I{} sh -c "cat {} | nc termbin.com 9999 | xargs -r0 printf '{} uploaded to %s'"
