version: '2'
services:
    btcd:
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
        build: 
            context: btcd/
        expose:
            - "18336"
        volumes:
            - shared-volume:/rpc
    lnd:
        environment:
            - RPCUSER=devuser
            - RPCPASS=devpass
        build: 
            context: ../
            dockerfile: docker/lnd/Dockerfile
        expose:
            - "10009"
            - "10011"
        volumes:
            - shared-volume:/rpc
        links:
            - btcd
volumes:
  shared-volume: {}
